CREATE TABLE users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT NOT NULL,
	email TEXT NOT NULL,
	password TEXT NOT NULL,
    mfa_enabled INTEGER NOT NULL
);

CREATE TABLE mfatoken(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	mfacode TEXT NOT NULL,
	user TEXT NOT NULL,
	mfatime TEXT NOT NULL
);